language: php
php:
  - 5.6
env:
  - DB=mysql

before_script:
  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS hello_world_test;" -uroot; fi

install: composer install

script: phpunit --bootstrap init_autoloader.php --coverage-text tests/

#deploy:
#  provider: opsworks
#  access-key-id: ACCESS-KEY-ID
#  secret-access-key: SECRET-ACCESS-KEY
# app-id: APP-ID
  